name = "kky-update-api"
main = "src/index.js"
compatibility_date = "2026-05-18"
workers_dev = false

routes = [
  { pattern = "update.zerokky.com/api/*", zone_name = "zerokky.com" },
  { pattern = "update.zerokky.com/family-browser*", zone_name = "zerokky.com" },
  { pattern = "update.zerokky.com/kky-tool/user-access.json*", zone_name = "zerokky.com" }
]

[[d1_databases]]
binding = "CONFIG_DB"
database_name = "kky-policy-config"
database_id = "c741173b-5844-4b32-ade9-f41642427da4"

[vars]
GITHUB_OWNER = "zerokky11"
GITHUB_REPO = "Release"
GITHUB_BRANCH = "main"
ALLOWED_ORIGINS = "https://update.zerokky.com,http://localhost:8787"
CONFIG_FALLBACK_TO_GITHUB = "true"
USAGE_RETENTION_DAYS = "90"
